### ISSUE TITLE
Recipes don't show in RoughlyEnoughItems

### ISSUE THREAD

**Issue by liabri** [Patbox/BiomeTechnologies#4]
As shown below there is no mod found by the name, to confirm I tried @biome and just searching for the biome converter & essences, with nothing showing up.
![image](https://user-images.githubusercontent.com/40229335/199830828-a3ac9aec-647f-4d23-ae78-58aac9f6af30.png)

**Comment by Patbox** [comment]
Depending on which mods you use, using JEI or EMI should just work

**Comment by Patbox** [comment]
Installing latest polymer should resolve that
